feat: Перенесены правила для тестов
kaluga-astral/style-guide pull request #13
Opened 2024-02-26 05:57 UTC by AndTem

2024-02-26 08:44 UTC, aiekseu requested changes

2024-02-26 08:44 UTC, aiekseu commented on docs/rules/tests/structure.md
> +  });
```suggestion
    it('Увеличивается при добавлении товаров до успешного выполнения запроса');

    it('Откатывается в исходное при ошибке запроса на добавления товаров в корзину');

    it('Уменьшается при удалении товаров до успешного выполнения запроса');

    it('Откатывается в исходное при ошибке запроса на удаление товаров из корзины');
  });
```

2024-02-26 08:44 UTC, aiekseu commented on docs/rules/tests/naming.md
> +### Тест-кейс должен начинаться с большой буквы
```suggestion
## Тест-кейс должен начинаться с большой буквы
```

2024-02-26 08:44 UTC, aiekseu commented on docs/rules/tests/naming.md
> +### Тест-кейсы описываются на русском языке
```suggestion
## Тест-кейсы описываются на русском языке
```

2024-02-26 08:44 UTC, aiekseu commented on docs/rules/tests/naming.md
> +### Нельзя указывать длинные значения в названиях тест-кейсов
```suggestion
## Нельзя указывать длинные значения в названиях тест-кейсов
```

2024-02-26 08:44 UTC, aiekseu commented on docs/rules/tests/naming.md
> +### Для указания значения параметра используется формат `PARAM_NAME=VALUE`
```suggestion
## Для указания значения параметра используется формат `PARAM_NAME=VALUE`
```

2024-02-27 13:40 UTC, aiekseu approved these changes

2024-02-28 06:25 UTC, sk-iv approved these changes

2024-02-28 08:26 UTC, merged